REM - HACER UNA COPIA DE ESTE .BAT Y CAMBIAR LOS VALORES DE LAS VARIABLES
REM - POR LOS QUE USEIS EN VUESTRA BASE DE DATOS

setx DB_HOST "localhost" -m
setx DB_USER "root" -m
setx DB_PASS "" -m
setx DB_NAME "ceti" -m
setx DB_PORT "3306" -m

pause
