REM - HACER UNA COPIA DE ESTE .BAT Y CAMBIAR LOS VALORES DE LAS VARIABLES
REM - POR LOS QUE USEIS EN VUESTRA BASE DE DATOS

setx DB_HOST "localhost" -M
setx DB_USER "root" -M
setx DB_PASS "" -M
setx DB_NAME "eshop_pps" -M
setx DB_PORT "3306" -M

pause
